(define (domain gripper-strips-4ops)
(:requirements :adl :equality :negative-preconditions)
(:types 	tile position - object
)

(:predicates (at ?a - tile ?b - position ?c - position)
	(blank ?a - position ?b - position)
	(inc ?a - position ?b - position)
	(dec ?a - position ?b - position)
)

(:action move-up
	:parameters (?a - position ?b - position ?c - position ?d - tile)
	:precondition (and (at ?d ?a ?b)
	(blank ?a ?c)(not (= ?a ?c))
	(not (= ?a ?b))
	(not (= ?b ?c)))
	:effect (and (at ?d ?a ?c)
		(blank ?a ?b)
		(inc ?a ?b)
		(inc ?b ?a)
		(not (at ?d ?a ?b))
		(not (blank ?a ?c)) 
		))

(:action move-down
	:parameters (?a - position ?b - position ?c - position ?d - tile)
	:precondition (and (at ?d ?a ?b)
	(blank ?a ?c)
	(blank ?b ?a)
	(dec ?a ?b)
	(dec ?b ?a)
	(inc ?b ?a)(not (= ?a ?c))
	(not (= ?a ?b))
	(not (= ?b ?c)))
	:effect (and (at ?d ?a ?c)
		(blank ?a ?b)
		(not (at ?d ?a ?b))
		(not (blank ?a ?c))
		(not (blank ?b ?a))
		(not (dec ?a ?b))
		(not (dec ?b ?a))
		(not (inc ?b ?a)) 
		))

(:action move-left
	:parameters (?a - position ?b - position ?c - position ?d - tile)
	:precondition (and (at ?d ?a ?b)
	(blank ?b ?a)
	(blank ?b ?c)
	(blank ?c ?b)
	(dec ?a ?b)
	(dec ?b ?a)
	(dec ?c ?b)
	(inc ?a ?b)
	(inc ?b ?a)
	(inc ?b ?c)
	(inc ?c ?b)(not (= ?a ?c))
	(not (= ?a ?b))
	(not (= ?b ?c)))
	:effect (and (at ?d ?c ?b)
		(blank ?a ?b)
		(blank ?b ?a)
		(dec ?a ?b)
		(inc ?a ?b)
		(inc ?b ?a)
		(not (at ?d ?a ?b))
		(not (blank ?b ?a))
		(not (blank ?b ?c))
		(not (blank ?c ?b))
		(not (dec ?a ?b))
		(not (dec ?b ?a))
		(not (dec ?c ?b))
		(not (inc ?a ?b))
		(not (inc ?b ?a))
		(not (inc ?b ?c))
		(not (inc ?c ?b)) 
		))

(:action move-right
	:parameters (?a - position ?b - position ?c - position ?d - tile)
	:precondition (and (at ?d ?a ?b)
	(blank ?c ?b)
	(inc ?b ?a)
	(inc ?b ?c)
	(inc ?c ?b)(not (= ?a ?c))
	(not (= ?a ?b))
	(not (= ?b ?c)))
	:effect (and (at ?d ?c ?b)
		(blank ?a ?b)
		(not (at ?d ?a ?b))
		(not (blank ?c ?b))
		(not (inc ?b ?a))
		(not (inc ?b ?c))
		(not (inc ?c ?b)) 
		))

)