(define (domain gripper-strips)
(:requirements :adl :equality :negative-preconditions)
(:types 	room ball gripper - object
)

(:predicates (at-robby ?r - room)
	(at ?b - ball ?r - room)
	(free ?g - gripper)
	(carry ?b - ball ?g - gripper)
)

(:action move
	:parameters (?from - room ?to - room)
	:precondition (and (at-robby ?from)
	(at-robby ?to)
	(not (at-robby ?from))
	(not (at-robby ?to))(not (= ?from ?to)))
	:effect (and (at-robby ?from)
		(at-robby ?to)
		(not (at-robby ?from))
		(not (at-robby ?to)) 
		))

(:action pick
	:parameters (?ball - ball ?gripper - gripper ?room - room)
	:precondition (and (at ?ball ?room)
	(at-robby ?room)
	(carry ?ball ?gripper)
	(free ?gripper)
	(not (at-robby ?room))
	(not (carry ?ball ?gripper))
	(not (free ?gripper)))
	:effect (and (at ?ball ?room)
		(at-robby ?room)
		(carry ?ball ?gripper)
		(free ?gripper)
		(not (at ?ball ?room))
		(not (at-robby ?room))
		(not (carry ?ball ?gripper))
		(not (free ?gripper)) 
		))

(:action drop
	:parameters (?ball - ball ?gripper - gripper ?room - room)
	:precondition (and (at ?ball ?room)
	(at-robby ?room)
	(carry ?ball ?gripper)
	(free ?gripper)
	(not (at ?ball ?room))
	(not (at-robby ?room))
	(not (free ?gripper)))
	:effect (and (at ?ball ?room)
		(at-robby ?room)
		(carry ?ball ?gripper)
		(free ?gripper)
		(not (at ?ball ?room))
		(not (at-robby ?room))
		(not (carry ?ball ?gripper))
		(not (free ?gripper)) 
		))

)