(define (domain rover)
(:requirements :strips :typing :negative-preconditions :equality)
(:types 	rover waypoint store camera mode lander objective - object
)

(:predicates (at ?x - rover ?y - waypoint)
	(at_lander ?x - lander ?y - waypoint)
	(can_traverse ?r - rover ?x - waypoint ?y - waypoint)
	(equipped_for_soil_analysis ?r - rover)
	(equipped_for_rock_analysis ?r - rover)
	(equipped_for_imaging ?r - rover)
	(empty ?s - store)
	(have_rock_analysis ?r - rover ?w - waypoint)
	(have_soil_analysis ?r - rover ?w - waypoint)
	(full ?s - store)
	(calibrated ?c - camera ?r - rover)
	(supports ?c - camera ?m - mode)
	(available ?r - rover)
	(visible ?w - waypoint ?p - waypoint)
	(have_image ?m - mode ?o - objective ?r - rover)
	(communicated_soil_data ?w - waypoint)
	(communicated_rock_data ?w - waypoint)
	(communicated_image_data ?m - mode ?o - objective)
	(at_soil_sample ?w - waypoint)
	(at_rock_sample ?w - waypoint)
	(visible_from ?o - objective ?w - waypoint)
	(store_of ?r - rover ?s - store)
	(calibration_target ?i - camera ?o - objective)
	(on_board ?i - camera ?r - rover)
	(channel_free ?l - lander)
)

(:action navigate
	:parameters (?x - rover ?y - waypoint ?z - waypoint)
	:precondition (and (at ?x ?y)
	(available ?x)
	(not (at ?x ?z))
	(not (can_traverse ?x ?y ?z))
	(not (can_traverse ?x ?z ?y))
	(not (equipped_for_imaging ?x))
	(not (equipped_for_rock_analysis ?x))
	(not (equipped_for_soil_analysis ?x))
	(not (visible ?y ?z))
	(not (visible ?z ?y))(not (= ?y ?z)))
	:effect (and (at ?x ?z)
		(not (at ?x ?y)) 
		))

(:action sample_soil
	:parameters (?x - rover ?s - store ?p - waypoint)
	:precondition (and (at ?x ?p)
	(at_soil_sample ?p)
	(available ?x)
	(empty ?s)
	(not (communicated_soil_data ?p))
	(not (equipped_for_imaging ?x))
	(not (equipped_for_rock_analysis ?x))
	(not (equipped_for_soil_analysis ?x))
	(not (full ?s))
	(not (have_rock_analysis ?x ?p))
	(not (have_soil_analysis ?x ?p))
	(not (store_of ?x ?s)))
	:effect (and (full ?s)
		(have_soil_analysis ?x ?p)
		(not (at_soil_sample ?p))
		(not (empty ?s)) 
		))

(:action sample_rock
	:parameters (?x - rover ?s - store ?p - waypoint)
	:precondition (and (at ?x ?p)
	(at_rock_sample ?p)
	(available ?x)
	(empty ?s)
	(not (communicated_rock_data ?p))
	(not (communicated_soil_data ?p))
	(not (equipped_for_imaging ?x))
	(not (equipped_for_rock_analysis ?x))
	(not (equipped_for_soil_analysis ?x))
	(not (full ?s))
	(not (have_rock_analysis ?x ?p))
	(not (have_soil_analysis ?x ?p))
	(not (store_of ?x ?s)))
	:effect (and (full ?s)
		(have_rock_analysis ?x ?p)
		(not (at_rock_sample ?p))
		(not (empty ?s)) 
		))

(:action drop
	:parameters (?x - rover ?y - store)
	:precondition (and (available ?x)
	(full ?y)
	(not (empty ?y))
	(not (equipped_for_imaging ?x))
	(not (equipped_for_rock_analysis ?x))
	(not (equipped_for_soil_analysis ?x))
	(not (store_of ?x ?y)))
	:effect (and (empty ?y)
		(not (full ?y)) 
		))

(:action calibrate
	:parameters (?i - camera ?t - objective ?r - rover ?w - waypoint)
	:precondition (and (at ?r ?w)
	(available ?r)
	(not (calibration_target ?i ?t))
	(not (equipped_for_imaging ?r))
	(not (equipped_for_rock_analysis ?r))
	(not (equipped_for_soil_analysis ?r))
	(not (on_board ?i ?r))
	(not (visible_from ?t ?w)))
	:effect (and (calibrated ?i ?r) 
		))

(:action take_image
	:parameters (?i - camera ?m - mode ?o - objective ?r - rover ?p - waypoint)
	:precondition (and (at ?r ?p)
	(available ?r)
	(calibrated ?i ?r)
	(not (calibration_target ?i ?o))
	(not (communicated_image_data ?m ?o))
	(not (equipped_for_imaging ?r))
	(not (equipped_for_rock_analysis ?r))
	(not (equipped_for_soil_analysis ?r))
	(not (have_image ?m ?o ?r))
	(not (on_board ?i ?r))
	(not (supports ?i ?m))
	(not (visible_from ?o ?p)))
	:effect (and (not (calibrated ?i ?r)) 
		))

(:action communicate_soil_data
	:parameters (?l - lander ?r - rover ?p - waypoint ?x - waypoint ?y - waypoint)
	:precondition (and (at ?r ?x)
	(available ?r)
	(channel_free ?l)
	(communicated_rock_data ?p)
	(communicated_soil_data ?y)
	(have_soil_analysis ?r ?p)
	(not (at ?r ?p))
	(not (at ?r ?y))
	(not (at_lander ?l ?p))
	(not (at_lander ?l ?x))
	(not (at_lander ?l ?y))
	(not (at_rock_sample ?p))
	(not (at_rock_sample ?x))
	(not (at_rock_sample ?y))
	(not (at_soil_sample ?p))
	(not (at_soil_sample ?x))
	(not (at_soil_sample ?y))
	(not (can_traverse ?r ?p ?x))
	(not (can_traverse ?r ?p ?y))
	(not (can_traverse ?r ?x ?p))
	(not (can_traverse ?r ?x ?y))
	(not (can_traverse ?r ?y ?p))
	(not (can_traverse ?r ?y ?x))
	(not (communicated_rock_data ?y))
	(not (communicated_soil_data ?x))
	(not (equipped_for_imaging ?r))
	(not (equipped_for_rock_analysis ?r))
	(not (equipped_for_soil_analysis ?r))
	(not (have_rock_analysis ?r ?p))
	(not (have_rock_analysis ?r ?x))
	(not (have_rock_analysis ?r ?y))
	(not (have_soil_analysis ?r ?x))
	(not (have_soil_analysis ?r ?y))
	(not (visible ?p ?x))
	(not (visible ?p ?y))
	(not (visible ?x ?p))
	(not (visible ?x ?y))
	(not (visible ?y ?p))
	(not (visible ?y ?x))(not (= ?p ?x))
	(not (= ?p ?y))
	(not (= ?x ?y)))
	:effect (and (communicated_soil_data ?p) 
		))

(:action communicate_rock_data
	:parameters (?l - lander ?r - rover ?p - waypoint ?x - waypoint ?y - waypoint)
	:precondition (and (at ?r ?x)
	(available ?r)
	(channel_free ?l)
	(communicated_rock_data ?p)
	(have_rock_analysis ?r ?p)
	(not (at ?r ?p))
	(not (at ?r ?y))
	(not (at_lander ?l ?p))
	(not (at_lander ?l ?x))
	(not (at_lander ?l ?y))
	(not (at_rock_sample ?p))
	(not (at_rock_sample ?x))
	(not (at_rock_sample ?y))
	(not (at_soil_sample ?y))
	(not (can_traverse ?r ?p ?x))
	(not (can_traverse ?r ?p ?y))
	(not (can_traverse ?r ?x ?p))
	(not (can_traverse ?r ?x ?y))
	(not (can_traverse ?r ?y ?p))
	(not (can_traverse ?r ?y ?x))
	(not (communicated_rock_data ?y))
	(not (equipped_for_imaging ?r))
	(not (equipped_for_rock_analysis ?r))
	(not (equipped_for_soil_analysis ?r))
	(not (have_rock_analysis ?r ?y))
	(not (have_soil_analysis ?r ?p))
	(not (have_soil_analysis ?r ?x))
	(not (have_soil_analysis ?r ?y))
	(not (visible ?p ?x))
	(not (visible ?p ?y))
	(not (visible ?x ?p))
	(not (visible ?x ?y))
	(not (visible ?y ?p))
	(not (visible ?y ?x))(not (= ?p ?x))
	(not (= ?p ?y))
	(not (= ?x ?y)))
	:effect (and  
		))

(:action communicate_image_data
	:parameters (?l - lander ?m - mode ?o - objective ?r - rover ?x - waypoint ?y - waypoint)
	:precondition (and (at ?r ?x)
	(available ?r)
	(channel_free ?l)
	(not (at ?r ?y))
	(not (at_lander ?l ?x))
	(not (at_lander ?l ?y))
	(not (at_rock_sample ?y))
	(not (can_traverse ?r ?x ?y))
	(not (can_traverse ?r ?y ?x))
	(not (communicated_image_data ?m ?o))
	(not (communicated_rock_data ?y))
	(not (equipped_for_imaging ?r))
	(not (equipped_for_rock_analysis ?r))
	(not (equipped_for_soil_analysis ?r))
	(not (have_image ?m ?o ?r))
	(not (have_rock_analysis ?r ?y))
	(not (visible ?x ?y))
	(not (visible ?y ?x))
	(not (visible_from ?o ?x))
	(not (visible_from ?o ?y))(not (= ?x ?y)))
	:effect (and  
		))

)